### ISSUE TITLE
Nothing but "ERROR untrusted: unable to get signee: trust:: node not found" logs after storagenode update to v0.11.1

### ISSUE THREAD

**Issue by ReneSmeekes** [storj/storj#1934]
After a bit of quiet and the network wipe, today my logs just started flooding these messages.
It seems it's having trouble finding the satellite during an upload. I see no successful transfers in my logs, nor any disk usage or new bandwidth usage in my dashboard. These messages are all I get and they come in at high speed.

Restarting the node doesn't help.

```
2019-05-09T14:30:59.915Z        ERROR   untrusted: unable to get signee: trust:: node not found
        storj.io/storj/storagenode/piecestore.(*Endpoint).VerifyOrderLimitSignature:133
        storj.io/storj/storagenode/piecestore.(*Endpoint).VerifyOrderLimit:68
        storj.io/storj/storagenode/piecestore.(*Endpoint).Upload:151
        storj.io/storj/pkg/pb._Piecestore_Upload_Handler:602
        storj.io/storj/pkg/server.streamInterceptor:19
        google.golang.org/grpc.(*Server).processStreamingRPC:1182
        google.golang.org/grpc.(*Server).handleStream:1254
        google.golang.org/grpc.(*Server).serveStreams.func1.1:690
ERROR: 2019/05/09 14:31:08 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-05-09T14:31:08.481Z        ERROR   context canceled
2019-05-09T14:32:05.869Z        ERROR   context canceled
2019-05-09T14:32:24.877Z        ERROR   untrusted: unable to get signee: trust:: node not found
        storj.io/storj/storagenode/piecestore.(*Endpoint).VerifyOrderLimitSignature:133
        storj.io/storj/storagenode/piecestore.(*Endpoint).VerifyOrderLimit:68
        storj.io/storj/storagenode/piecestore.(*Endpoint).Upload:151
        storj.io/storj/pkg/pb._Piecestore_Upload_Handler:602
        storj.io/storj/pkg/server.streamInterceptor:19
        google.golang.org/grpc.(*Server).processStreamingRPC:1182
        google.golang.org/grpc.(*Server).handleStream:1254
        google.golang.org/grpc.(*Server).serveStreams.func1.1:690

```

**Comment by nerdatwork** [comment]
Nothing but Upload failed in the logs. Not a single successful upload.

**Comment by ReneSmeekes** [comment]
I did some digging through the code and found it was an issue with Kademlia lookups. I also noticed my neighborhood size hadn't changed at all since the update to v0.11.1. So I figured something was wrong with my Kademlia routing table. With advise from @stefanbenten I took the following steps to fix it.

1. Stop the node: `docker stop storagenode`
2. Rename the kademlia file in the storage path to kademlia.bak
3. Start the node again

It took a few seconds to get some nodes back in the routing table and then it started working again like a charm.

**Comment by stefanbenten** [comment]
This issue was resolved in the recent releases and i am going ahead and closing this issue.
If that error comes back, please reopen!

**Comment by PocketSam** [comment]
Seems it still present in V 0.14.13
I've got this version and lots of such errors in the log.

**Comment by ifraixedes** [comment]
We have seen it in the last release v0.15.2 and we already have a PR that will potentially mitigate the problem https://github.com/storj/storj/pull/2584
