### ISSUE TITLE
`link.staging.tardigradeshare.io` site is not trusted

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4325]
![image](https://user-images.githubusercontent.com/15882196/148364706-0b2b04bd-d4f8-4620-adf2-89e29bfd2c42.png)

**Comment by stefanbenten** [comment]
Fixed :) I'll inform the respective team to troubleshoot this further.

**Comment by nerdatwork** [comment]
The link still won't open though. The page simply wont load.

**Comment by stefanbenten** [comment]
Yep, thats another issue i am looking into. The cert is served correctly now tho. Its just the response that is not coming back.

**Comment by stefanbenten** [comment]
@nerdatwork should be working now.
